name: PulseOS Build Cloud

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y arch-install-scripts

      - name: Run mkarchiso via Docker (Privileged)
        run: |
          # Мы запускаем Arch Linux внутри привилегированного докера, 
          # чтобы у него были права на mount и chroot.
          docker run --privileged -v $(pwd):/workspace -w /workspace archlinux:latest bash -c "
            pacman -Syu --noconfirm archiso &&
            mkarchiso -v -w /tmp/work -o /workspace/out /workspace
          "

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: PulseOS-ISO
          path: out/*.iso
